# -*- coding: utf-8 -*-
# Generated by Django 4.2 on 2026-06-21
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Note: The actual tables are managed via Supabase SQL,
        # but we add Django model representations for completeness

        # Since we're using Supabase directly, we'll need to execute raw SQL
        # for the constraints and indexes. This migration file serves as
        # documentation of what needs to be done.

        # The actual SQL to be executed in Supabase:
        # -- Adicionar índice único para evitar agendamentos duplicados
        # CREATE UNIQUE INDEX idx_appointments_vehicle_date_time_unique
        # ON appointments (vehicle_id, date, time_slot)
        # WHERE status IN ('pendente', 'confirmado');
        #
        # -- Índices para melhorar performance das consultas de disponibilidade
        # CREATE INDEX idx_availability_slots_date_time ON availability_slots (date, time_slot);
        # CREATE INDEX idx_availability_slots_available ON availability_slots (is_available) WHERE is_available = true;
        # CREATE INDEX idx_appointments_vehicle_date_time ON appointments (vehicle_id, date, time_slot);
    ]